### ISSUE TITLE
Clean up FillTree

### ISSUE THREAD

**Issue by kirsty-duffy** [kirsty-duffy/uB-CC1pi#2]
- [x] Track length (and everything else, and shower variables) indexing should be the same as PFP index
- [x] Change variable names
- [x] Check all variables are filled how we expect/assume in DrawHists.C (Kirsty)

**Comment by AleshaDevitt** [comment]
Lined up all Sel_PFP var indices

**Comment by kirsty-duffy** [comment]
cutflow -> Marco_cutflow
isSelected -> Marco_selected
Sel_PFP -> TPCObj_PFP
NPFPs -> TPCObj_NPFPs
also for NTracks, NShowers
Sel_MCP_ID -> TPCObj_PFP_MCPid
Sel_MCP_PDG -> TPCObj_PFP_truePDG
tpcobj_blah -> TPCObj_blah
dqdx_trunc_uncalib -> TPCObj_PFP_track_dqdx_truncmean
topology -> TPCObj_beamnu_topology

?MCP_blah -> beamnu_MCP_blah?

Add comment where isSelected if statement closes

Add comment near MCP section saying that it's only for MCPs coming from true neutrino beam interactions

Change logic - add variables, set all to -9999 at start of loop, at end of loop have emplace_back(variable) for all tree variables.

Change PassesCC1piSelec to pseudo-cut in cutflow

Add MCP_KE (E - mass)
