### ISSUE TITLE
Data POT counting

### ISSUE THREAD

**Issue by AleshaDevitt** [kirsty-duffy/uB-CC1pi#22]
Add run and subrun branches to the module for data POT counting. More details here: https://www.evernote.com/l/AXaNt9ClhXBB-5RCGCvfcTqYVBequO1X-Yc

**Comment by kirsty-duffy** [comment]
I'm closing this issue - I think we have everything we need in the files now to do POT counting. We have the correct branches in the tree for MC, and for data we can use Zarko's script on the parent reco2 files. To do so:

1) Copy files.list in bookdir to files_parents.list
2) Type this up into a script and run on files_parents.list to produce a list of reco2 files that are parents of the files that you processed
```
#!/bin/bash

sed -i 's/reco2.*.root/reco2.root/g' $1
while read p; do 

  NAME=`basename $p`
  echo $NAME >> ${1}out

done < $1
```
3) Run Zarko's script to get the POT counting: /uboone/app/users/zarko/getDataInfo.py -v2 --file-list files_parents.list

For how to interpret the output of Zarko's script and convert into data/MC scaling factors, see https://microboone-docdb.fnal.gov/cgi-bin/private/RetrieveFile?docid=15204&filename=normalisation.pdf&version=1
