### ISSUE TITLE
Plots showing what selected tracks are

### ISSUE THREAD

**Issue by kirsty-duffy** [kirsty-duffy/uB-CC1pi#6]
- Plot showing event-by-event what the selected tracks (selected in reco) are (in truth PDG)
- Need to think about how exactly to show this. 2D histogram? Only works for 2 tracks. 1D histogram? Need to control number of bins.

**Comment by AleshaDevitt** [comment]
2D hist, with axis 1 being longest track PDG and axis 2 being second longest track pdg. Categories of mu, pi, p, other? Can expand "other" if necessary.
